EasyFind.WebApp/Controllers/TaskController.cs
using System;
using System.Web.Mvc;
using EasyFind.WebApp.Models;
using EasyFind.Common.Models.Enums;
using EasyFind.Logic.Services.Interfaces;
using EasyFind.Logic.Services.Implementations;

namespace EasyFind.WebApp.Controllers
{
    [Authorize]
    public class TaskController : Controller
    {
        private readonly IAvitoService _avitoService;

        public TaskController()
        {
            _avitoService = new AvitoService();
        }

        public ActionResult Index()
        {
            var model = new SearchCarModel()
            {
                AvitoCars = _avitoService.GetCarsBrands(),
                SitesNames = Enum.GetNames(typeof(SitesEnum))
            };
            return View(model);
        }
    }
}

EasyFind.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink(" ", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Главная", "Index", "Home")</li>
                    <li>@Html.ActionLink("Поиск", "Index", "Task")</li>
                    <li>@Html.ActionLink("Контакты", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - EasyFind</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>